# Generated by Django 2.0.13 on 2019-11-15 14:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IllustrationLayoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOccasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='found_at',
            new_name='collection_venue',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='usage',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title',
            new_name='title_translation',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='year',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(to='publications.Author'),
        ),
        migrations.AddField(
            model_name='publication',
            name='collection_country',
            field=django_countries.fields.CountryField(default='Netherlands', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='collection_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='copyrights',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='publication',
            name='country',
            field=django_countries.fields.CountryField(default='Netherlands', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='nr_of_pages',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='printed_by',
            field=models.CharField(default='Emmanuel', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='title_subtitle_european',
            field=models.CharField(default='something cyrillic', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='title_subtitle_transcription',
            field=models.CharField(default='some title', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='venue',
            field=models.CharField(default='restaurant venue', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1850), publications.models.max_value_current_year], verbose_name='year_of_birth'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='language',
        ),
        migrations.AddField(
            model_name='publication',
            name='language',
            field=models.ManyToManyField(to='publications.Language'),
        ),
        migrations.AddField(
            model_name='publication',
            name='church',
            field=models.ManyToManyField(to='publications.Church'),
        ),
        migrations.AddField(
            model_name='publication',
            name='currently_owned_by',
            field=models.ManyToManyField(to='publications.Owner'),
        ),
        migrations.AddField(
            model_name='publication',
            name='illustration_and_layout',
            field=models.ManyToManyField(to='publications.IllustrationLayoutType'),
        ),
        migrations.AddField(
            model_name='publication',
            name='special_occasion',
            field=models.ManyToManyField(to='publications.SpecialOccasion'),
        ),
    ]
