# Generated by Django 2.0.13 on 2019-11-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20191115_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='country',
        ),
        migrations.AddField(
            model_name='publication',
            name='title_original',
            field=models.CharField(default='Default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='publications.Country'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_city',
            field=models.OneToOneField(default='Eindhoven', on_delete=django.db.models.deletion.CASCADE, to='publications.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_country',
            field=models.OneToOneField(default='Netherlands', on_delete=django.db.models.deletion.CASCADE, to='publications.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='translator',
            field=models.ManyToManyField(to='publications.Translator'),
        ),
    ]
