# Generated by Django 2.2.8 on 2019-12-13 14:57

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_auto_20191213_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Countrys',
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='publication_country', chained_model_field='countrys', null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.City'),
        ),
    ]
