# Generated by Django 2.0.13 on 2019-11-13 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import publications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('year_of_birth', models.IntegerField(validators=[django.core.validators.MinValueValidator(1850), publications.models.max_value_current_year], verbose_name='year')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('L', publications.models.WritingDirection('L')), ('R', publications.models.WritingDirection('R'))], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('CI', publications.models.LocationType('CI')), ('CO', publications.models.LocationType('CO')), ('AR', publications.models.LocationType('AR'))], default='CI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=30)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), publications.models.max_value_current_year], verbose_name='year')),
                ('found_at', models.CharField(max_length=30)),
                ('usage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('type', models.CharField(choices=[('P', publications.models.DocumentType('P')), ('W', publications.models.DocumentType('W')), ('I', publications.models.DocumentType('I')), ('V', publications.models.DocumentType('V'))], default='P', max_length=1)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='publications.Publication')),
                ('public', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('location_on_disk', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='genre',
            field=models.ManyToManyField(to='publications.Genre'),
        ),
    ]
