# Generated by Django 2.0.13 on 2019-11-08 15:36

import django.core.validators
from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), publications.models.max_value_current_year], verbose_name='year'),
        ),
    ]
