# Generated by Django 2.0.13 on 2019-11-20 11:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='church',
            new_name='affiliated_church',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='collection_venue',
            new_name='collection_venue_and_city',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='special_occasion',
            new_name='connected_to_special_occasion',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='genre',
            new_name='content_genre',
        ),
        migrations.AddField(
            model_name='publication',
            name='contact_info',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='content_description',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='description_of_illustration',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='form_of_publication',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='image_details',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='possible_donor',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publishing_organisation',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='publication_country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='publications.City'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Country'),
        ),
    ]
