# Generated by Django 2.0.13 on 2019-11-20 12:54

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20191120_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='illustrationlayouttype',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='collection_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='publication',
            name='collection_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='collection_venue_and_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contact_info',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_of_illustration',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='form_of_publication',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image_details',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='nr_of_pages',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='possible_donor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='printed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='publication_country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='publications.City'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Country'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publishing_organisation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_original',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_subtitle_european',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_subtitle_transcription',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_translation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='publication',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialoccasion',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translator',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='translator',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
