# Generated by Django 2.0.13 on 2019-11-15 16:23

import django.core.validators
from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20191115_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1850), publications.models.max_value_current_year], verbose_name='year_of_birth'),
        ),
    ]
