# Generated by Django 2.0.13 on 2019-11-20 13:01

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20191120_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='publication_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.City'),
        ),
    ]
