# Generated by Django 2.0.13 on 2019-11-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20191120_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
