# Generated by Django 2.2 on 2019-11-27 15:57

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20191120_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='form_of_publication',
            field=models.CharField(choices=[('P', publications.models.FormOfPublication('P')), ('S', publications.models.FormOfPublication('S')), ('T', publications.models.FormOfPublication('T')), ('O', publications.models.FormOfPublication('O'))], default=None, max_length=1),
        ),
    ]
