# Generated by Django 2.2 on 2019-11-27 16:15

from django.db import migrations, models
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20191127_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='form_of_publication',
            field=models.CharField(blank=True, choices=[('P', publications.models.FormOfPublication('P')), ('S', publications.models.FormOfPublication('S')), ('T', publications.models.FormOfPublication('T')), ('O', publications.models.FormOfPublication('O')), (None, publications.models.FormOfPublication(None))], max_length=1),
        ),
    ]
