# Generated by Django 2.2 on 2019-11-29 09:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_auto_20191127_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
