# Generated by Django 2.2 on 2019-11-29 09:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20191129_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
