# Generated by Django 2.2.8 on 2019-12-13 14:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20191129_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name_plural': 'churches'},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Country'),
        ),
    ]
