# Generated by Django 2.2.8 on 2019-12-13 15:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_auto_20191213_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(default='here', max_length=2),
            preserve_default=False,
        ),
    ]
