# Generated by Django 2.2.8 on 2019-12-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_auto_20191218_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='illustration_and_layout',
            new_name='illustration_and_layout_type',
        ),
    ]
