# Generated by Django 2.2.8 on 2020-01-03 14:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_auto_20200103_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
            preserve_default=False,
        ),
    ]
