# Generated by Django 2.2.8 on 2020-01-03 15:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0022_auto_20200103_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
