# Generated by Django 2.2.8 on 2020-01-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0025_auto_20200115_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='collection_date',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
