# Generated by Django 2.2.9 on 2020-01-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0028_auto_20200124_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='direction',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=5),
        ),
    ]
