# Generated by Django 2.2.9 on 2020-01-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0029_auto_20200129_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_country',
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_country',
            field=models.ManyToManyField(to='publications.Country'),
        ),
    ]
