# Generated by Django 2.2.9 on 2020-01-29 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0031_auto_20200129_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publications.Country'),
        ),
    ]
