# Generated by Django 2.2.9 on 2020-01-29 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0032_auto_20200129_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
