# Generated by Django 2.2.9 on 2020-01-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0033_auto_20200129_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='publication_country',
        ),
    ]
