# Generated by Django 2.2.9 on 2020-01-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0036_publication_publication_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country'),
        ),
    ]
