# Generated by Django 2.2.9 on 2020-01-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0037_auto_20200131_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_city',
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.City'),
        ),
    ]
