# Generated by Django 2.2.9 on 2020-01-31 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('publications', '0039_remove_publication_publication_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country'),
        ),
    ]
