# Generated by Django 2.2.10 on 2020-02-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('publications', '0044_auto_20200203_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lastname',
        ),
        migrations.AddField(
            model_name='publication',
            name='ISBN_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='publication',
            name='translated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_from', to='countries_plus.Country'),
        ),
        migrations.AddField(
            model_name='publication',
            name='type_of_collection',
            field=models.CharField(choices=[('O', 'Original'), ('T', 'Translated')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.ManyToManyField(to='publications.Keyword'),
        ),
    ]
