# Generated by Django 2.2.10 on 2020-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0045_auto_20200219_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='type_of_collection',
        ),
        migrations.AddField(
            model_name='publication',
            name='is_translated',
            field=models.NullBooleanField(),
        ),
    ]
