# Generated by Django 2.2.10 on 2020-02-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0046_auto_20200221_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translator',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='translator',
            name='lastname',
        ),
    ]
