# Generated by Django 2.2.10 on 2020-02-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0047_auto_20200221_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='translated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translated_from', to='publications.Language'),
        ),
    ]
