# Generated by Django 2.2.10 on 2020-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0048_auto_20200224_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='direction',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], max_length=5),
        ),
    ]
