# Generated by Django 2.2.10 on 2020-03-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0049_auto_20200224_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='possible_donor',
            new_name='donor',
        ),
    ]
