# Generated by Django 2.2.10 on 2020-03-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0050_auto_20200306_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='comments',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
