# Generated by Django 2.2.10 on 2020-03-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0051_auto_20200306_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
