# Generated by Django 2.2.10 on 2020-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0052_publication_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_translated',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'Yes'), (False, 'No')]),
        ),
    ]
