# Generated by Django 2.2.10 on 2020-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0055_auto_20200306_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='extra_info',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='translator',
            name='name_original_language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
