# Generated by Django 2.2.10 on 2020-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0056_auto_20200309_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_source', models.CharField(blank=True, max_length=100)),
                ('contact_of_source', models.CharField(blank=True, max_length=100)),
                ('copyright_issues', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='image_details',
        ),
        migrations.AddField(
            model_name='publication',
            name='image_details',
            field=models.ManyToManyField(to='publications.ImageDetails'),
        ),
    ]
