# Generated by Django 2.2.10 on 2020-03-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0057_auto_20200309_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedetails',
            old_name='contact_of_source',
            new_name='photographer',
        ),
        migrations.RenameField(
            model_name='imagedetails',
            old_name='name_of_source',
            new_name='source_of_photo_or_illustration',
        ),
        migrations.RemoveField(
            model_name='imagedetails',
            name='copyright_issues',
        ),
    ]
