# Generated by Django 2.2.10 on 2020-03-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0058_auto_20200316_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='is_translated',
            new_name='is_a_translation',
        ),
    ]
