# Generated by Django 2.2.10 on 2020-05-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0062_auto_20200504_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/2020/05/04/13/16/11/'),
        ),
    ]
