# Generated by Django 2.2.10 on 2020-05-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0065_auto_20200504_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='general_comments',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='publication',
            name='team_comments',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
