# Generated by Django 2.2.10 on 2020-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0066_auto_20200507_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='general_comments',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='publication',
            name='team_comments',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
