# Generated by Django 2.2.10 on 2020-05-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0067_auto_20200507_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='other_comments',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
