# Generated by Django 2.2.10 on 2020-05-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0068_publication_other_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='title_subtitle_European',
        ),
        migrations.AddField(
            model_name='publication',
            name='title_original2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_original3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_original4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_original5',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_subtitle_transcription2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_subtitle_transcription3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_subtitle_transcription4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_subtitle_transcription5',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_translation2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_translation3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_translation4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_translation5',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
