# Generated by Django 2.2.13 on 2020-06-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0069_auto_20200522_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='coverfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='publications.UploadedFile'),
        ),
    ]
