# Generated by Django 2.2.10 on 2020-07-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0071_auto_20200717_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='filecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filecategory', to='publications.FileCategory'),
        ),
    ]
