# Generated by Django 2.2.13 on 2020-07-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0073_auto_20200720_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='imagecontent',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='imagecontent',
            field=models.ManyToManyField(to='publications.ImageContent'),
        ),
    ]
