# Generated by Django 2.2.13 on 2020-07-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0074_auto_20200720_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='imagecontent',
            new_name='imagecontents',
        ),
    ]
