# Generated by Django 2.2.13 on 2020-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0075_auto_20200720_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategory',
            name='order_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
