# Generated by Django 2.2.10 on 2020-09-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0079_filecategory_list_view_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='imagecontents',
            new_name='image_contents',
        ),
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='description',
            new_name='image_title',
        ),
    ]
