# Generated by Django 2.2.13 on 2020-09-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0080_auto_20200904_1613'),
        ('publications', '0077_auto_20200723_1040'),
    ]

    operations = [
    ]
