# Generated by Django 2.2.13 on 2020-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0081_auto_20200921_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
