# Generated by Django 2.2.13 on 2020-10-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0082_publication_publication_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_date',
        ),
    ]
