# Generated by Django 2.2.13 on 2020-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0083_remove_publication_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='currency',
            field=models.CharField(choices=[('0', 'USD: United States Dollar'), ('1', 'CAD: Canadian Dollar'), ('2', 'AUD: Australian Dollar'), ('3', 'EUR: Euro'), ('4', 'GBP: Pound sterling'), ('5', 'SEK: Swedish krona'), ('6', 'EGP: Egyptian pound'), ('7', 'LBP: Libanese pound'), ('8', 'ETB: Ethopian birr'), ('9', 'ERN: Eritrean nakfa'), ('10', 'ILS: Israeli shekel'), ('11', 'AMD: Armenian dram')], default='0', max_length=25),
        ),
    ]
