# Generated by Django 2.2.13 on 2020-11-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0081_merge_20200916_1526'),
        ('publications', '0084_publication_currency'),
    ]

    operations = [
    ]
