# Generated by Django 2.2.13 on 2021-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0085_merge_20201130_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_stub',
            field=models.BooleanField(default=False),
        ),
    ]
