# Generated by Django 2.2.13 on 2021-01-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0087_auto_20210122_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='title_original',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title_original2',
            new_name='title2',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title_original3',
            new_name='title3',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title_original4',
            new_name='title4',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title_original5',
            new_name='title5',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='translators',
        ),
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(to='publications.Author'),
        ),
        migrations.AddField(
            model_name='publication',
            name='translator',
            field=models.ManyToManyField(to='publications.Translator'),
        ),
    ]
