# Generated by Django 2.2.13 on 2021-01-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0088_auto_20210125_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='translators',
            new_name='translator',
        ),
    ]
