# Generated by Django 2.2.13 on 2021-01-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0088_auto_20210125_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='translator',
            new_name='translators',
        ),
    ]
