# Generated by Django 2.2.13 on 2021-01-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0087_auto_20210125_1753'),
        ('publications', '0089_auto_20210125_1724'),
    ]

    operations = [
    ]
