# Generated by Django 2.2.13 on 2021-02-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0088_auto_20210129_1822'),
        ('publications', '0091_publication_date_created'),
    ]

    operations = [
    ]
