# Generated by Django 2.2.13 on 2021-02-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0092_merge_20210201_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='translator',
            new_name='translators',
        ),
    ]
