# Generated by Django 2.2.13 on 2021-02-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0093_auto_20210201_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
