# Generated by Django 2.2.13 on 2021-02-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0094_uploadedfile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='image_contents_char',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
