# Generated by Django 2.2.13 on 2021-02-22 14:10

from django.db import migrations

def transfer_image_contents(apps, schema_editor):
    UploadedFile = apps.get_model('publications', 'UploadedFile')
    for file in UploadedFile.objects.all():
        str_list = []
        for ic in file.image_contents.all():
            str_list.append(ic.name)
        file.image_contents_char = ','.join(str_list)
        file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0095_uploadedfile_image_contents_char'),
    ]

    operations = [
        migrations.RunPython(transfer_image_contents),
    ]
