# Generated by Django 2.2.13 on 2021-02-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0096_transfer_image_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='image_contents',
        ),
        migrations.DeleteModel(
            name='ImageContent',
        ),
    ]
