# Generated by Django 2.2.13 on 2021-02-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0097_auto_20210222_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='image_contents_char',
            new_name='image_contents',
        ),
    ]
