# Generated by Django 2.2.13 on 2021-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0098_auto_20210222_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='other_comments',
        ),
        migrations.AlterField(
            model_name='publication',
            name='general_comments',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='team_comments',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
