# Generated by Django 2.2.20 on 2021-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0099_auto_20210406_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_periodical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='ongoing',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AddField(
            model_name='publication',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
