# Generated by Django 2.2.20 on 2021-04-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0100_auto_20210419_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='search_terms_appear_in',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
