# Generated by Django 2.2.20 on 2021-05-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0101_publication_search_terms_appear_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='search_terms_appear_in',
            new_name='search_term_appear_in',
        ),
    ]
