# Generated by Django 2.2.20 on 2021-05-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0102_auto_20210503_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='search_term_appear_in',
        ),
    ]
