# Generated by Django 2.2.20 on 2021-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0103_remove_publication_search_term_appear_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='general_comments',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='team_comments',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
