# Generated by Django 2.2.24 on 2021-07-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0105_auto_20210705_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
    ]
