# Generated by Django 2.2.24 on 2021-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0107_auto_20210709_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='contact_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='currency',
            field=models.CharField(choices=[('0', 'unknown'), ('1', 'EUR: Euro'), ('2', 'GBP: Pound sterling'), ('3', 'SEK: Swedish krona'), ('4', 'NLD: Dutch gulden'), ('5', 'AUS: Austrian Schiling'), ('6', 'GRM: German Mark'), ('7', 'MAL: Maltese Lira'), ('8', 'BEF: Belgian Franc'), ('9', 'GRD: Greek Drachma'), ('10', 'CYP: Cypriot Pound'), ('11', 'IRP: Irish Pound'), ('12', 'PTE: Portugese Escudo'), ('13', 'ESK: Estonian Kroon'), ('14', 'ITL: Italian Lira'), ('15', 'SLK: Slovak Koruna'), ('16', 'FNM: Finnish Markka'), ('17', 'LAL: Latvian Lats'), ('18', 'SLT: Slovenian Tolar'), ('19', 'FRF: French Franc'), ('20', 'LIL: Lituanian Litas'), ('21', 'SPP: Spanish Peseta'), ('22', 'LXF: Luxembourgian Franc'), ('23', 'ALL: Albanian Lek'), ('24', 'BAM: Bosnia and Herzegovina convertible mark'), ('25', 'BGN: Bulgarian Lev'), ('26', 'HRK: Croatian Kuna'), ('27', 'CZK: Czech Koruna'), ('28', 'DKK: Danish Krone'), ('29', 'HUF: Hungarian Forint'), ('30', 'ISK: Icelandic Krona'), ('31', 'CHF: Swiss Franc'), ('32', 'MDL: Moldovan Leu'), ('33', 'MKD: Second Macedonian Denar'), ('34', 'NOK: Norwegian Krone'), ('35', 'PLN: Polish Zloty'), ('36', 'RON: Romanian Leu'), ('37', 'RSD: Serbian Dinar'), ('38', 'SEK: Swedish Kronar'), ('39', 'CHF: Swiss Franc'), ('40', 'TRY: Turkish Lira'), ('41', 'UAH: Ukrainian Hryvnia'), ('42', 'USD: United States Dollar'), ('43', 'CAD: Canadian Dollar'), ('44', 'AUD: Australian Dollar'), ('45', 'EGP: Egyptian pound'), ('46', 'LBP: Libanese pound'), ('47', 'ETB: Ethopian birr'), ('48', 'ERN: Eritrean nakfa'), ('49', 'ILS: Israeli shekel'), ('50', 'AMD: Armenian dram'), ('51', 'GEL: Geogrian Lari'), ('52', 'BYN: Belarusian Ruble'), ('53', 'RUB: Russian Ruble')], default='0', max_length=25),
        ),
    ]
