# Generated by Django 2.2.24 on 2023-01-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0109_church_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='collection_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_city', to='publications.City'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='main_color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='image_content_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_content_category', to='publications.ImageContentCategory'),
        ),
    ]
