# Generated by Django 2.2.24 on 2023-07-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0110_auto_20230120_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategory',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='collection_venue_and_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Collection venue'),
        ),
    ]
