# Generated by Django 2.2.24 on 2023-07-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0111_auto_20230728_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
