# Generated by Django 2.2.24 on 2023-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0112_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='coordinates_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='coordinates_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
